/**
 * Design Tokens - Auto-generated from design-tokens.json
 * DO NOT EDIT THIS FILE DIRECTLY - Edit design-tokens.json instead
 * Then run: npm run generate-tokens
 */

export const designTokens = {
  "color": {
    "brand": {
      "primary": "#1E3A52",
      "secondary": "#9AAAB5",
      "accentGreen": "#005C4D",
      "accentGreen100": "#B2E6DF",
      "accentGreen300": "#008A75",
      "accentGreen500": "#005C4D",
      "accentGreen700": "#004739",
      "accentGreen900": "#00332A"
    },
    "accent": {
      "green100": "#B2E6DF",
      "green300": "#008A75",
      "green500": "#005C4D",
      "green600": "#004F42",
      "green700": "#004739",
      "green900": "#00332A",
      "blue500": "#007BFF"
    },
    "text": {
      "default": "#1E3A52",
      "heading": "#1E3A52",
      "body": "#4A5568",
      "subtle": "#6C7A89",
      "inverse": "#FFFFFF",
      "error": "#CC0000",
      "success": "#005C4D",
      "link": "#007BFF"
    },
    "background": {
      "page": "#F9FAFB",
      "card": "#FFFFFF",
      "focus": "#E0E6EB",
      "successLight": "#B2E6DF",
      "subtle": "#f9fafb"
    },
    "border": {
      "light": "#e5e7eb",
      "medium": "#d1d5db",
      "subtle": "#f3f4f6"
    }
  },
  "spacing": {
    "xxs": 4,
    "xs": 8,
    "s": 16,
    "m": 24,
    "l": 32,
    "xl": 48
  },
  "typography": {
    "fontFamily": {
      "primary": "Lato"
    },
    "fontSize": {
      "xxs": 12,
      "xs": 14,
      "s": 16,
      "m": 16,
      "l": 24,
      "xl": 32,
      "xxl": 40
    },
    "fontWeight": {
      "regular": "400",
      "semibold": "600",
      "bold": "700"
    }
  },
  "borderRadius": {
    "none": "0",
    "default": "4px",
    "round": "50%"
  },
  "shadow": {
    "default": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "lifted": "0 8px 16px rgba(0, 0, 0, 0.15)"
  },
  "shadowMobile": {
    "default": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 2
      },
      "shadowOpacity": 0.1,
      "shadowRadius": 4,
      "elevation": 2
    },
    "lifted": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 8
      },
      "shadowOpacity": 0.15,
      "shadowRadius": 16,
      "elevation": 8
    },
    "card": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 4
      },
      "shadowOpacity": 0.1,
      "shadowRadius": 6,
      "elevation": 4
    },
    "cardLg": {
      "shadowColor": "#000000",
      "shadowOffset": {
        "width": 0,
        "height": 10
      },
      "shadowOpacity": 0.1,
      "shadowRadius": 15,
      "elevation": 10
    }
  }
};

// Re-export for convenience
export default designTokens;
