#!/usr/bin/env node

/**
 * Generate platform-specific design tokens from design-tokens.json
 * - Generates design-tokens.js for JavaScript/TypeScript consumption
 * - Keeps SCSS variables in sync (manual for now, could be automated)
 */

const fs = require('fs');
const path = require('path');

const tokensPath = path.join(__dirname, '../design-tokens.json');
const outputJsPath = path.join(__dirname, '../design-tokens.js');

// Read design tokens
const tokens = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

// Generate JavaScript/TypeScript module
const jsContent = `/**
 * Design Tokens - Auto-generated from design-tokens.json
 * DO NOT EDIT THIS FILE DIRECTLY - Edit design-tokens.json instead
 * Then run: npm run generate-tokens
 */

export const designTokens = ${JSON.stringify(tokens, null, 2)};

// Re-export for convenience
export default designTokens;
`;

// Write JavaScript file
fs.writeFileSync(outputJsPath, jsContent, 'utf8');

console.log('✅ Generated design-tokens.js');
console.log('📝 Note: SCSS variables should be manually synced if needed');
console.log('   Location: scss/_variables.scss');
